apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops-python
  namespace: devops-demo
  labels:
    app: demo-devops-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-devops-python
  template:
    metadata:
      labels:
        app: demo-devops-python
    spec:
      containers:
      - name: demo-devops-python
        image: devwho/demo-devops-python:latest
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DATABASE_NAME
          value: db/db.sqlite3
        - name: DJANGO_ALLOWED_HOSTS
          value: "*"
        volumeMounts:
        - name: db-volume
          mountPath: /app/db
        readinessProbe:
          httpGet:
            path: /api/users/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/users/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 5
      volumes:
      - name: db-volume
        emptyDir: {}


