apiVersion: v1
kind: Service
metadata:
  name: demo-devops-python-service
  namespace: devops-demo
spec:
  type: NodePort
  selector:
    app: demo-devops-python
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080

